字段 | 说明 
------|------
competition_process|世界杯赛程
id|赛程id
home_id|主队id，对应team_info中的id
visiting_id|客队id，对应team中的id
home_team|主场队伍
visiting_team|客场队伍
competitiong_time|比赛时间
result|比赛结果
type|比赛类型（小组赛，淘汰赛等）

In [1]:
import pandas as pd

competition_process = pd.read_csv(r"D:\worldcup\competition_process.csv")
competition_process.head()

,id,home_id,visiting_id,home_team,visiting_team,competition_time,result,type,create_time,update_time
0,49,1,2,俄罗斯,沙特阿拉伯,2018-06-14 23:00:00,-,小组赛,2018/4/16 09:40:29,2018/4/16 09:40:29
1,50,3,4,埃及,乌拉圭,2018-06-15 20:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
2,51,1,3,俄罗斯,埃及,2018-06-20 02:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
3,52,4,2,乌拉圭,沙特阿拉伯,2018-06-20 23:00:00,-,小组赛,2018/4/16 09:40:31,2018/4/16 09:40:31
4,53,2,3,沙特阿拉伯,埃及,2018-06-25 22:00:00,-,小组赛,2018/4/16 09:40:36,2018/4/16 09:40:36
5,54,1,4,俄罗斯,乌拉圭,2018-06-25 22:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
6,55,8,7,摩洛哥,伊朗,2018-06-15 23:00:00,-,小组赛,2018/4/16 11:23:54,2018/4/16 11:23:54
7,56,5,6,葡萄牙,西班牙,2018-06-16 02:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
8,57,5,8,葡萄牙,摩洛哥,2018-06-20 20:00:00,-,小组赛,2018/4/16 11:23:59,2018/4/16 11:23:59
9,58,7,6,伊朗,西班牙,2018-06-21 02:00:00,-,小组赛,2018/4/16 11:23:41,2018/4/16 11:23:41
10,59,7,5,伊朗,葡萄牙,2018-06-26 02:00:00,-,小组赛,2018/4/16 11:23:49,2018/4/16 11:23:49
11,60,6,8,西班牙,摩洛哥,2018-06-26 02:00:00,-,小组赛,2018/4/16 11:24:03,2018/4/16 11:24:03
12,61,10,12,法国,澳大利亚,2018-06-16 18:00:00,-,小组赛,2018/4/16 11:26:45,2018/4/16 11:26:45
13,62,11,9,秘鲁,丹麦,2018-06-16 23:59:00,-,小组赛,2018/4/16 11:24:28,2018/4/16 11:24:28
14,63,9,12,丹麦,澳大利亚,2018-06-21 20:00:00,-,小组赛,2018/4/16 11:26:48,2018/4/16 11:26:48
15,64,10,11,法国,秘鲁,2018-06-21 23:00:00,-,小组赛,2018/4/16 11:25:24,2018/4/16 11:25:24
16,65,12,11,澳大利亚,秘鲁,2018-06-26 22:00:00,-,小组赛,2018/4/16 11:26:50,2018/4/16 11:26:50
17,66,9,10,丹麦,法国,2018-06-26 22:00:00,-,小组赛,2018/4/16 11:26:16,2018/4/16 11:26:16
18,67,14,13,阿根廷,冰岛,2018-06-16 21:00:00,-,小组赛,2018/4/16 11:27:49,2018/4/16 11:27:49
19,68,15,16,克罗地亚,尼日利亚,2018-06-17 03:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
20,69,14,15,阿根廷,克罗地亚,2018-06-22 02:00:00,-,小组赛,2018/4/16 11:27:57,2018/4/16 11:27:57
21,70,16,13,尼日利亚,冰岛,2018-06-22 23:00:00,-,小组赛,2018/4/16 11:27:17,2018/4/16 11:27:17
22,71,13,15,冰岛,克罗地亚,2018-06-27 02:00:00,-,小组赛,2018/4/16 11:29:40,2018/4/16 11:29:40
23,72,16,14,尼日利亚,阿根廷,2018-06-27 02:00:00,-,小组赛,2018/4/16 11:29:28,2018/4/16 11:29:28
24,73,20,17,哥斯达黎加,塞尔维亚,2018-06-17 20:00:00,-,小组赛,2018/4/16 11:31:47,2018/4/16 11:31:47
25,74,19,18,巴西,瑞士,2018-06-18 02:00:00,-,小组赛,2018/4/16 11:30:51,2018/4/16 11:30:51
26,75,19,20,巴西,哥斯达黎加,2018-06-22 20:00:00,-,小组赛,2018/4/16 11:31:38,2018/4/16 11:31:38
27,76,17,18,塞尔维亚,瑞士,2018-06-23 02:00:00,-,小组赛,2018/4/16 11:31:20,2018/4/16 11:31:20
28,77,17,19,塞尔维亚,巴西,2018-06-28 02:00:00,-,小组赛,2018/4/16 11:31:24,2018/4/16 11:31:24
29,78,18,20,瑞士,哥斯达黎加,2018-06-28 02:00:00,-,小组赛,2018/4/16 11:31:44,2018/4/16 11:31:44
30,79,22,23,德国,墨西哥,2018-06-17 23:00:00,-,小组赛,2018/4/16 11:33:48,2018/4/16 11:33:48
31,80,21,24,瑞典,韩国,2018-06-18 20:00:00,-,小组赛,2018/4/16 11:32:14,2018/4/16 11:32:14
32,81,24,23,韩国,墨西哥,2018-06-23 23:00:00,-,小组赛,2018/4/16 11:32:39,2018/4/16 11:32:39
33,82,22,21,德国,瑞典,2018-06-24 02:00:00,-,小组赛,2018/4/16 11:33:26,2018/4/16 11:33:26
34,83,24,22,韩国,德国,2018-06-27 22:00:00,-,小组赛,2018/4/16 11:33:31,2018/4/16 11:33:31
35,84,23,21,墨西哥,瑞典,2018-06-27 22:00:00,-,小组赛,2018/4/16 11:32:34,2018/4/16 11:32:34
36,85,25,27,比利时,巴拿马,2018-06-18 23:00:00,-,小组赛,2018/4/16 11:34:13,2018/4/16 11:34:13
37,86,28,26,突尼斯,英格兰,2018-06-19 02:00:00,-,小组赛,2018/4/16 11:34:57,2018/4/16 11:34:57
38,87,25,28,比利时,突尼斯,2018-06-23 20:00:00,-,小组赛,2018/4/16 11:34:20,2018/4/16 11:34:20
39,88,26,27,英格兰,巴拿马,2018-06-24 20:00:00,-,小组赛,2018/4/16 11:34:35,2018/4/16 11:34:35
40,89,26,25,英格兰,比利时,2018-06-29 02:00:00,-,小组赛,2018/4/16 11:34:41,2018/4/16 11:34:41
41,90,27,28,巴拿马,突尼斯,2018-06-29 02:00:00,-,小组赛,2018/4/16 11:34:30,2018/4/16 11:34:30
42,91,30,32,哥伦比亚,日本,2018-06-19 20:00:00,-,小组赛,2018/4/16 11:35:58,2018/4/16 11:35:58
43,92,29,31,波兰,塞内加尔,2018-06-19 23:00:00,-,小组赛,2018/4/16 11:35:45,2018/4/16 11:35:45
44,93,32,31,日本,塞内加尔,2018-06-24 23:00:00,-,小组赛,2018/4/16 11:35:05,2018/4/16 11:35:05
45,94,29,30,波兰,哥伦比亚,2018-06-25 02:00:00,-,小组赛,2018/4/16 11:35:53,2018/4/16 11:35:53
46,95,32,29,日本,波兰,2018-06-28 22:00:00,-,小组赛,2018/3/12 14:59:10,2018/3/12 14:59:10
47,96,31,30,塞内加尔,哥伦比亚,2018-06-28 22:00:00,-,小组赛,2018/4/16 11:35:49,2018/4/16 11:35:49

### 比赛历史信息
字段 | 说明 
------|------
team_id|队伍标题，对应team_info中的id
team_name|队伍名称
home_team|主场队伍
visiting_team|客场队伍
type|比赛类型
time|比赛时间
result|比赛结果
foul|犯规 关于team_id的比赛信息（下同）
yellow_card|黄牌
red_card|红牌
possession|控球率
shot|射门（射正）
pass|传球（成功）
pass_rate|传球成功率
most|过人次数
score|表现评分

In [197]:
historical_record = pd.read_csv(r"D:\worldcup\historical_record.csv")
del historical_record['id']
del historical_record['create_time']
del historical_record['update_time']
historical_record = historical_record.drop_duplicates() 
historical_record.loc[(historical_record["team_name"] == '法国') & ((historical_record["home_team"] == '西班牙') | (historical_record["visiting_team"] == '西班牙'))]

,team_id,team_name,home_team,visiting_team,type,time,result,foul,yellow_card,red_card,possession,shot,pass,pass_rate,most,score
665,10,法国,法国,西班牙,国际友谊,2017/3/29 03:00:00,0-2,17,2,0,0.41,8(2),439(371),0.85,1,4
699,10,法国,法国,西班牙,国际友谊,2014/9/5 03:00:00,1-0,9,0,0,0.42,10(5),0(0),0.00,0,2
717,10,法国,法国,西班牙,欧洲预选,2013/3/27 04:00:00,0-1,21,3,1,0.24,15(3),0(0),0.00,0,5
721,10,法国,西班牙,法国,欧洲预选,2012/10/17 03:00:00,1-1,10,2,2,0.50,7(3),0(0),0.00,0,3
725,10,法国,西班牙,法国,欧洲杯,2012/6/24 02:45:00,2-0,12,2,1,0.45,4(1),0(0),0.00,0,3

### 队伍信息

In [3]:
team_info = pd.read_csv(r"D:\worldcup\team_info.csv")
team_info.head()

,id,name,group,group_gamecount,group_game_win,group_game_draw,group_game_lose,group_game_goal_diff,score,rank,is_top_16,is_top_8,is_top_4,create_time,update_time
0,1,俄罗斯,A,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:59:12,2018/3/9 13:59:12
1,2,沙特阿拉伯,A,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 09:54:02,2018/3/9 09:54:02
2,3,埃及,A,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:31,2018/3/7 10:42:33
3,4,乌拉圭,A,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:36,2018/3/7 10:42:39
4,5,葡萄牙,B,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:05,2018/3/7 10:42:05
5,6,西班牙,B,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:06,2018/3/7 10:42:06
6,7,伊朗,B,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:41:52,2018/3/9 13:41:52
7,8,摩洛哥,B,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:41:49,2018/3/9 13:41:49
8,9,丹麦,C,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:42:20,2018/3/9 13:42:20
9,10,法国,C,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:42:34,2018/3/9 13:42:34
10,11,秘鲁,C,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:13,2018/3/7 10:42:13
11,12,澳大利亚,C,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:42:32,2018/3/9 13:42:32
12,13,冰岛,D,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:43:16,2018/3/9 13:43:16
13,14,阿根廷,D,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:43:12,2018/3/9 13:43:12
14,15,克罗地亚,D,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:16,2018/3/7 10:42:16
15,16,尼日利亚,D,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:17,2018/3/7 10:42:17
16,17,塞尔维亚,E,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:44:21,2018/3/9 13:44:21
17,18,瑞士,E,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:19,2018/3/7 10:42:19
18,19,巴西,E,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:44:07,2018/3/9 13:44:07
19,20,哥斯达黎加,E,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:44:05,2018/3/9 13:44:05
20,21,瑞典,F,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:45:23,2018/3/9 13:45:23
21,22,德国,F,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:45:27,2018/3/9 13:45:27
22,23,墨西哥,F,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:45:21,2018/3/9 13:45:21
23,24,韩国,F,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:24,2018/3/7 10:42:24
24,25,比利时,G,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:25,2018/3/7 10:42:25
25,26,英格兰,G,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:46:18,2018/3/9 13:46:18
26,27,巴拿马,G,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:46:14,2018/3/9 13:46:14
27,28,突尼斯,G,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:46:12,2018/3/9 13:46:12
28,29,波兰,H,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:28,2018/3/7 10:42:28
29,30,哥伦比亚,H,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:46:42,2018/3/9 13:46:42
30,31,塞内加尔,H,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/9 13:46:38,2018/3/9 13:46:38
31,32,日本,H,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,2018/3/7 10:42:31,2018/3/7 10:42:31

### 世界排名

In [5]:
team_rank = pd.read_csv(r"D:\worldcup\team_rank.csv")
team_rank.head()

,id,team_name,local_rank,world_rank,rating,average_rank,average_rating,one_year_rank_change,one_year_rating_change,matches_total,matches_home,matches_away,matches_neutral,matches_win,matches_lose,matches_draw,goal_for,goal_against
0,1,巴西,1,1,2113,4,1993,0,22,960,336,312,312,607,157,196,2085,880
1,2,德国,2,2,2109,8,1907,1,71,938,407,380,151,548,200,190,2114,1100
2,3,西班牙,3,3,2031,7,1936,3,52,678,297,266,115,397,129,152,1347,615
3,4,葡萄牙,4,4,1995,19,1779,4,64,593,277,225,91,284,173,136,991,696
4,5,法国,5,5,1989,17,1771,-1,-20,823,422,308,93,399,252,172,1451,1171
5,6,阿根廷,6,6,1984,5,1983,-4,-61,1001,352,391,258,535,217,249,1881,1060
6,7,英格兰,7,7,1933,4,1982,2,4,1033,448,482,103,603,191,239,2435,1019
7,8,比利时,8,8,1928,24,1734,5,22,759,367,330,62,317,279,163,1319,1244
8,9,哥伦比亚,9,9,1927,51,1584,1,1,553,163,201,189,215,190,148,695,666
9,10,秘鲁,10,12,1881,35,1667,7,48,613,236,221,156,197,263,153,769,882
10,11,乌拉圭,11,13,1866,12,1875,-1,-49,916,308,394,214,399,295,222,1457,1155
11,12,瑞士,11,13,1866,28,1674,3,9,784,378,349,57,273,342,169,1133,1341
12,13,克罗地亚,13,16,1857,12,1874,-1,-24,295,121,127,47,157,58,80,518,282
13,14,墨西哥,14,17,1856,20,1775,-6,-61,883,269,239,375,454,223,206,1600,917
14,15,波兰,15,18,1843,29,1709,0,-9,818,345,370,103,355,260,203,1401,1107
15,16,丹麦,16,19,1842,20,1793,15,125,801,363,360,78,365,275,161,1470,1128
16,17,瑞典,17,20,1818,16,1796,8,60,1018,442,463,113,500,298,220,2066,1354
17,18,冰岛,18,21,1813,81,1407,5,47,426,185,207,34,134,213,79,512,708
18,19,伊朗,19,22,1799,41,1645,2,26,580,201,165,214,321,118,141,1089,460
19,20,塞尔维亚,20,23,1770,20,1784,10,41,752,265,368,119,350,238,164,1408,1042
20,21,韩国,21,25,1760,37,1679,-4,-31,939,302,229,408,511,197,231,1711,862
21,22,塞尔维亚,22,27,1752,59,1578,8,39,567,186,217,164,241,168,158,749,563
22,23,哥斯达黎加,23,31,1745,34,1695,-9,-41,678,230,242,206,316,200,162,1221,770
23,24,澳大利亚,24,35,1728,36,1650,1,18,533,231,195,107,270,149,114,1077,600
24,25,日本,25,41,1707,62,1476,-11,-47,705,278,176,251,329,224,152,1225,848
25,26,俄罗斯,26,43,1698,22,1739,-4,7,694,250,327,117,361,151,182,1222,680
26,27,尼日利亚,27,44,1696,40,1666,5,29,601,211,238,152,275,152,174,900,614
27,28,摩洛哥,28,45,1691,44,1652,15,89,604,257,199,148,281,146,177,873,528
28,29,巴拿马,29,48,1671,102,1334,-1,0,473,171,177,125,148,208,117,570,743
29,30,埃及,30,50,1659,34,1671,-6,-23,750,306,246,198,381,191,178,1330,802
30,31,突尼斯,31,53,1624,53,1602,16,52,640,291,216,133,263,194,183,910,710
31,32,沙特阿拉伯,32,69,1567,77,1490,-4,-19,685,278,122,285,337,192,156,1107,734

### 算法

In [1]:
import pandas as pd
import datetime
import numpy as np

def sigmoid(inX):  
    return 1.0/(1+np.exp(-inX))  

def goal_fiff(team1, team2, competition_time):
    #historical_record = pd.read_csv(r"D:\worldcup\historical_record.csv")
    historical_record = pd.read_csv(r"D:\worldcup\historical_record.csv")
    del historical_record['id']
    del historical_record['create_time']
    del historical_record['update_time']
    #去重
    historical_record = historical_record.drop_duplicates().reset_index(drop = True)
    #处理result为净胜球    
    for i in range(len(historical_record)):
        num1 = historical_record.loc[i, 'result'].split('-')[0]
        num2 = historical_record.loc[i, 'result'].split('-')[1]
        if historical_record.loc[i, 'home_team'] == historical_record.loc[i, 'team_name']:
            historical_record.loc[i, 'result'] = int(num1) - int(num2)
        else:
            historical_record.loc[i, 'result'] = int(num2) - int(num1)
    #选出team1和team2
    historical_record_1 = historical_record.loc[historical_record["team_name"] == team1]
    historical_record_2 = historical_record.loc[historical_record["team_name"] == team2]
    e_df = set(historical_record_1['home_team'].tolist()).union(set(historical_record_1['visiting_team'].tolist()))
    s_df = set(historical_record_2['home_team'].tolist()).union(set(historical_record_2['visiting_team'].tolist()))
    e_union_s = e_df.intersection(s_df)
    #print(e_union_s)
    #选出即和team1交手又和team2交手的队伍
    int_inf_2 = historical_record_2.loc[historical_record_2["visiting_team"].isin(e_union_s) | historical_record_2["home_team"].isin(e_union_s)]
    int_inf_1 = historical_record_1.loc[historical_record_1["visiting_team"].isin(e_union_s) | historical_record_1["home_team"].isin(e_union_s)]
    concat_e_s = pd.concat([int_inf_1, int_inf_2]).reset_index(drop=True)  
    
    #print(e_df)
    #设置比赛开始时间
    concat_e_s_sle = concat_e_s.loc[: , ['team_name', 'home_team', 'visiting_team', 'time', 'result', 'score']]
    concat_e_s_sle['time'] = pd.to_datetime(concat_e_s_sle['time'])
    start_date_str = competition_time
    start_date = datetime.datetime.strptime(start_date_str, '%Y-%m-%d %H:%M:%S')
    #sigmode处理时间，得出权重
    concat_e_s_sle['sec_from_start_to_data'] = (concat_e_s_sle.loc[:, 'time']-start_date).dt.total_seconds()  
    concat_e_s_sle['sfstd_non'] = concat_e_s_sle.loc[:, ['sec_from_start_to_data']].apply(lambda x: (x - np.mean(x)) / (np.std(x)))

    concat_e_s_sle['wight'] = sigmoid(concat_e_s_sle['sfstd_non'])
    #净胜球与权重结合
    concat_e_s_sle['result_wight'] = concat_e_s_sle['result'] * concat_e_s_sle['wight']
    #计算结合平均值
    union_1 = pd.DataFrame({'team_name':[],'oppose_team':[],'mean_result_1':[]})
    union_2 = pd.DataFrame({'team_name':[],'oppose_team':[],'mean_result_2':[]})
    for i in e_union_s:
        if i != team1:
            mean_1 = concat_e_s_sle.loc[(concat_e_s_sle['team_name'] == team1)&((concat_e_s_sle['home_team'] == i) | (concat_e_s_sle['visiting_team'] == i))].loc[:, 'result_wight'].mean()
            union_1 = pd.concat([union_1, pd.DataFrame({'team_name':[team1],'oppose_team':[i],'mean_result_1':[mean_1]})])
        if i != team2:
            mean_2 = concat_e_s_sle.loc[(concat_e_s_sle['team_name'] == team2)&((concat_e_s_sle['home_team'] == i) | (concat_e_s_sle['visiting_team'] == i))].loc[:, 'result_wight'].mean()
            union_2 = pd.concat([union_2, pd.DataFrame({'team_name':[team2],'oppose_team':[i],'mean_result_2':[mean_2]})])
        
        
    union = union_1.merge(union_2, on = 'oppose_team')
    #print(union)
    
    #team1与team2直接对抗结果
    mean_1_2 = concat_e_s_sle.loc[(concat_e_s_sle['team_name'] == team1)&((concat_e_s_sle['home_team'] == team2) | (concat_e_s_sle['visiting_team'] == team2))].loc[:, 'result_wight'].mean()
    op_1_2 = pd.DataFrame({'team_name':[team1],'oppose_team':[team2],'mean_result_1':[mean_1_2]})
    mean_2_1 = concat_e_s_sle.loc[(concat_e_s_sle['team_name'] == team2)&((concat_e_s_sle['home_team'] == team1) | (concat_e_s_sle['visiting_team'] == team1))].loc[:, 'result_wight'].mean()
    op_2_1 = pd.DataFrame({'team_name':[team2],'oppose_team':[team1],'mean_result_2':[mean_2_1]})
    #合并所有
    union_all = pd.concat([union, op_2_1, op_1_2]).fillna(0)
    #print(pd.concat([union, op_2_1, op_1_2]).fillna(0))
    
    res = (union_all['mean_result_1'] - union_all['mean_result_2']).mean()
    res_e_s = pd.DataFrame({'team1':[team1], 'team2':[team2], 'competition_time':[competition_time], '净胜球':[res]})
    return res_e_s

#goal_fiff('西班牙', '法国', '2018-06-14 23:00:00')

### 结果

In [2]:
competition_process = pd.read_csv(r"D:\worldcup\competition_process.csv")
result = pd.DataFrame({'team1':[] , 'team2':[], 'competition_time':[], '净胜球':[]})
for i in range(len(competition_process)):
    result = pd.concat([result, goal_fiff(competition_process.loc[i, 'home_team'], competition_process.loc[i, 'visiting_team'], competition_process.loc[i, 'competition_time'])])
    #print(i)
result

      competition_time  team1  team2       净胜球
0  2018-06-14 23:00:00    俄罗斯  沙特阿拉伯  0.824845
0  2018-06-15 20:00:00     埃及    乌拉圭 -0.275923
0  2018-06-20 02:00:00    俄罗斯     埃及  0.299574
0  2018-06-20 23:00:00    乌拉圭  沙特阿拉伯  0.498543
0  2018-06-25 22:00:00  沙特阿拉伯     埃及 -0.141609
0  2018-06-25 22:00:00    俄罗斯    乌拉圭  0.098682
0  2018-06-15 23:00:00    摩洛哥     伊朗 -0.107328
0  2018-06-16 02:00:00    葡萄牙    西班牙 -0.464226
0  2018-06-20 20:00:00    葡萄牙    摩洛哥  0.277806
0  2018-06-21 02:00:00     伊朗    西班牙 -0.326099
0  2018-06-26 02:00:00     伊朗    葡萄牙 -0.063409
0  2018-06-26 02:00:00    西班牙    摩洛哥  0.373414
0  2018-06-16 18:00:00     法国   澳大利亚  0.880400
0  2018-06-16 23:59:00     秘鲁     丹麦 -0.496810
0  2018-06-21 20:00:00     丹麦   澳大利亚  0.541176
0  2018-06-21 23:00:00     法国     秘鲁  0.561171
0  2018-06-26 22:00:00   澳大利亚     秘鲁 -0.520624
0  2018-06-26 22:00:00     丹麦     法国 -0.621076
0  2018-06-16 21:00:00    阿根廷     冰岛  0.710319
0  2018-06-17 03:00:00   克罗地亚   尼日利亚 -0.000198
0  2018-06-22 02:00:00    阿根廷   克罗地亚  0.264655
0  2018-06-22 23:00:00   尼日利亚     冰岛  0.122830
0  2018-06-27 02:00:00     冰岛   克罗地亚 -0.089284
0  2018-06-27 02:00:00   尼日利亚    阿根廷 -0.392545
0  2018-06-17 20:00:00  哥斯达黎加   塞尔维亚 -0.074098
0  2018-06-18 02:00:00     巴西     瑞士  0.341689
0  2018-06-22 20:00:00     巴西  哥斯达黎加  0.825737
0  2018-06-23 02:00:00   塞尔维亚     瑞士 -0.002520
0  2018-06-28 02:00:00   塞尔维亚     巴西 -0.799753
0  2018-06-28 02:00:00     瑞士  哥斯达黎加  0.078777
0  2018-06-17 23:00:00     德国    墨西哥  0.382727
0  2018-06-18 20:00:00     瑞典     韩国  0.187302
0  2018-06-23 23:00:00     韩国    墨西哥 -0.221690
0  2018-06-24 02:00:00     德国     瑞典  0.789900
0  2018-06-27 22:00:00     韩国     德国 -0.723100
0  2018-06-27 22:00:00    墨西哥     瑞典 -0.204403
0  2018-06-18 23:00:00    比利时    巴拿马  0.369149
0  2018-06-19 02:00:00    突尼斯    英格兰 -0.333333
0  2018-06-23 20:00:00    比利时    突尼斯  0.378684
0  2018-06-24 20:00:00    英格兰    巴拿马  0.620594
0  2018-06-29 02:00:00    英格兰    比利时 -0.190353
0  2018-06-29 02:00:00    巴拿马    突尼斯  0.000000
0  2018-06-19 20:00:00   哥伦比亚     日本  0.677823
0  2018-06-19 23:00:00     波兰   塞内加尔 -0.064392
0  2018-06-24 23:00:00     日本   塞内加尔  0.050117
0  2018-06-25 02:00:00     波兰   哥伦比亚 -0.429224
0  2018-06-28 22:00:00     日本     波兰  0.111394
0  2018-06-28 22:00:00   塞内加尔   哥伦比亚 -0.746772

In [3]:
result.to_csv(r"D:\worldcup\result.csv", index_label=False)